import 'dart:typed_data';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:plinkyhub/models/saved_wavetable.dart';
import 'package:plinkyhub/state/authentication_notifier.dart';
import 'package:plinkyhub/state/saved_wavetables_notifier.dart';
import 'package:plinkyhub/widgets/plinky_button.dart';

class UploadWavetableTab extends ConsumerStatefulWidget {
  const UploadWavetableTab({this.onUploaded, super.key});

  final VoidCallback? onUploaded;

  @override
  ConsumerState<UploadWavetableTab> createState() =>
      _UploadWavetableTabState();
}

class _UploadWavetableTabState
    extends ConsumerState<UploadWavetableTab> {
  final _nameController = TextEditingController();
  final _descriptionController = TextEditingController();
  bool _isPublic = true;
  Uint8List? _uf2Bytes;
  String? _fileName;
  bool _isUploading = false;

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  void _resetForm() {
    setState(() {
      _nameController.clear();
      _descriptionController.clear();
      _isPublic = true;
      _uf2Bytes = null;
      _fileName = null;
      _isUploading = false;
    });
  }

  Future<void> _pickUf2File() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['uf2', 'UF2'],
      withData: true,
    );

    if (result != null && result.files.single.bytes != null) {
      final file = result.files.single;
      setState(() {
        _uf2Bytes = file.bytes;
        _fileName = file.name;
        if (_nameController.text.isEmpty) {
          _nameController.text = file.name.replaceAll(
            RegExp(r'\.[uU][fF]2$'),
            '',
          );
        }
      });
    }
  }

  Future<void> _upload() async {
    final userId = ref.read(authenticationProvider).user?.id;
    if (_uf2Bytes == null ||
        _fileName == null ||
        userId == null) {
      return;
    }

    setState(() => _isUploading = true);

    try {
      final baseName =
          _fileName!.substring(0, _fileName!.lastIndexOf('.'));
      final timestamp =
          DateTime.now().millisecondsSinceEpoch;
      final storageName = '${baseName}_$timestamp.uf2';

      final wavetable = SavedWavetable(
        id: '',
        userId: userId,
        name: _nameController.text.trim(),
        filePath: '$userId/$storageName',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        description: _descriptionController.text.trim(),
        isPublic: _isPublic,
      );

      await ref
          .read(savedWavetablesProvider.notifier)
          .saveWavetable(
            wavetable,
            uf2Bytes: _uf2Bytes!,
          );

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Wavetable uploaded')),
        );
        _resetForm();
        widget.onUploaded?.call();
      }
    } on Exception catch (e) {
      debugPrint('Failed to upload wavetable: $e');
      setState(() => _isUploading = false);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(e.toString())),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 500),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Text(
                'Upload a wavetab.uf2 file generated by the '
                'Plinky wavetable tool. The tool takes 15 '
                'single-cycle WAV files (c0.wav through c14.wav) '
                'and produces a UF2 file that can be loaded '
                'onto your Plinky.',
                style: Theme.of(context)
                    .textTheme
                    .bodyMedium
                    ?.copyWith(
                      color: Theme.of(context)
                          .colorScheme
                          .onSurfaceVariant,
                    ),
              ),
              const SizedBox(height: 8),
              Text(
                'Get the wavetable tool at '
                'github.com/plinkysynth/wavetable',
                style: Theme.of(context)
                    .textTheme
                    .bodySmall
                    ?.copyWith(
                      color: Theme.of(context)
                          .colorScheme
                          .primary,
                    ),
              ),
              const SizedBox(height: 16),
              PlinkyButton(
                onPressed: _isUploading
                    ? null
                    : _pickUf2File,
                icon: Icons.memory,
                label: _fileName ?? 'Choose wavetab.uf2 file',
              ),
              const SizedBox(height: 16),
              TextField(
                controller: _nameController,
                decoration: const InputDecoration(
                  labelText: 'Name',
                  border: OutlineInputBorder(),
                ),
              ),
              const SizedBox(height: 16),
              TextField(
                controller: _descriptionController,
                decoration: const InputDecoration(
                  labelText: 'Description',
                  border: OutlineInputBorder(),
                ),
                maxLines: 3,
              ),
              const SizedBox(height: 16),
              SwitchListTile(
                title: const Text('Share with community'),
                value: _isPublic,
                onChanged: _isUploading
                    ? null
                    : (value) =>
                        setState(() => _isPublic = value),
              ),
              const SizedBox(height: 8),
              Text(
                'By uploading, you confirm that you own this '
                'wavetable or have the right to use and '
                'distribute it (e.g. under a Creative Commons '
                'licence or similar terms).',
                style: Theme.of(context)
                    .textTheme
                    .bodySmall
                    ?.copyWith(
                      color: Theme.of(context)
                          .colorScheme
                          .onSurfaceVariant,
                    ),
              ),
              const SizedBox(height: 16),
              PlinkyButton(
                onPressed: _isUploading || _uf2Bytes == null
                    ? null
                    : _upload,
                icon: _isUploading
                    ? Icons.hourglass_empty
                    : Icons.upload,
                label:
                    _isUploading ? 'Uploading...' : 'Upload',
              ),
            ],
          ),
        ),
      ),
    );
  }
}
